module_order:
  -fastqc:
    name: "FastQC (raw)"
    anchor: "fastqc_raw"
    path_filters:
      - "pretrim_fastqc/*_fastqc.zip"
  - cutadapt
  - fastqc:
    name: "FastQC (trimmed)"
    anchor: "fastqc_trimmed"
    
  - hisat2
  - htseq

