module_order:
    - fastqc:
        name: 'FastQC (raw)'
        anchor: 'fastqc_raw'
        path_filters_exclude:
            - '*_val_[12]_fastqc.zip'
            - '*_trimmed_fastqc.zip'
            - '*_repaired_R[12]_fastqc.zip'
            - '*_rmrRNA_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed)'
        anchor: 'fastqc_trimmed'
        path_filters:
            - '*_val_[12]_fastqc.zip'
            - '*_trimmed_fastqc.zip'
    - sortmerna
    - fastqc:
        name: 'FastQC (sortMeRNA)'
        anchor: 'fastqc_sortmerna'
        path_filters:
            - '*_repaired_R[12]_fastqc.zip'
            - '*_rmrRNA_fastqc.zip'
    - hisat2:
        contents: 'HISAT2 summary stats'
        shared: true
    - htseq